################# English language ################
[en]
languageName = "English"
languageCode = "en-US"
contentDir = "content/english"
weight = 1

################ Espanol language ##################
[es]
languageName = "Espanol"
languageCode = "es-es"
contentDir = "content/Espanol"
weight = 2

################ Italian language #################
[it]
languageName = "Italiano"
languageCode = "it-IT"
contentDir = "content/italian"
weight = 3

################ German language ##################
[de]
languageName = "German"
languageCode = "de-at"
contentDir = "content/german"
weight = 4